version: "3.7"
services:
  database:
    build:
      context: ./MySQL
    container_name: spinners-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=spinners
    ports:
      - 3306:3306      
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spinners_network
  devcontainer-python:
    build:
      context: ./devcontainer-python
    container_name: spinners-dev-python
    volumes:
      - .:/dev-workspace # bind mount git repository to folder dev-workspace on container
    networks:
      - spinners_network
    command: sleep infinity #otherwise it will exit immediately
  devcontainer-csharp:
    build:
      context: ./devcontainer-csharp
    container_name: spinners-dev-csharp
    volumes:
      - .:/dev-workspace
    networks:
      - spinners_network
    command: sleep infinity
  recipes:
    build:
      context: ./container-recipes
    container_name: spinners-recipes
    networks:
      - spinners_network
    depends_on:
      - database
      - gateway
  recipes_mock:
    build:
      context: ./container-recipes
      dockerfile: ../container-recipes-mock/Dockerfile
    container_name: spinners-recipes-mock
    networks:
      - spinners_network
    depends_on:
      - database
      - gateway
  gateway:
    build:
      context: ./node-red
    container_name: spinners-node-red
    networks:
      - spinners_network
    ports:
      - 1880:1880
      - 54840:54840

volumes:
  mysql_data:
    name: mysql_data    
  node_red_data:
    name: node_red_data
    driver: local
    
networks:
  spinners_network:
    name: spinners_network

