services:
  database:
    build:
      context: ./MySQL
    container_name: spinners-mysql
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
    ports:
      - 3306:3306      
    volumes:
      - mysql_data:/data
    networks:
      - spinners_network
volumes:
  mysql_data:
    name: mysql_data
networks:
  spinners_network:
    name: spinners_network

