version: "3.7"
services:
  database:
    build:
      context: ./MySQL
    container_name: spinners-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=employees
    ports:
      - 3306:3306      
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spinners_network
volumes:
  mysql_data:
    name: mysql_data
networks:
  spinners_network:
    name: spinners_network

