FROM python:latest

# upgrade pip version
RUN pip install --upgrade pip

# Install dependencies
# (don't know which will be needed yet)
#COPY requirements.txt /tmp/requirements.txt
#RUN pip install -r /tmp/requirements.txt && rm /tmp/requirements.txt

RUN pip install asyncua
RUN pip install transitions
RUN pip install mysql-connector-python
